RA-03 сверстал кнопки навигации
Lapadoga/RecipeApp pull request #1
Opened 2024-10-24 13:48 UTC by Lapadoga

2024-10-25 16:34 UTC, Churickoid requested changes
Не выполнил 8 пункт задания, в themes.xml нужно прописать параметры
<item name="android:statusBarColor">@color/</item>
      <item name="android:navigationBarColor">@color/</item>

2024-10-25 16:34 UTC, Churickoid commented on app/src/main/res/values/styles.xml
> +    <style name="Widget.Material3.Button.StyleNavButton">
Все локальные стили правильнее называть без лишней вложенности. Этот стиль не имеет никакого отношения к библиотеки Widget.Material3. Такой нейминг запутает других разработчиков, не очевидно, что это локальный стиль.
Оставь только StyleNavButton и StyleTitle14 в названиях стилей и дальше придерживайся такого нейминга.

Здесь еще не хватает наследования от Widget.Material3.Button, нужно прописать parent = "..."

2024-10-25 16:34 UTC, Churickoid commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14sp</item>
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки. 
Стилей это тоже касается

2024-10-25 16:34 UTC, Churickoid commented on app/src/main/res/values/styles.xml
> +        <item name="cornerRadius">8dp</item>
Все значения не забываем выносить в ресурсы и переиспользоват

2024-10-25 16:34 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +        get() = _binding ?: throw IllegalStateException("Binding for activity main is null")
Лучше стараться продумать подходящее поведение по-умолчанию. В уроке реализовывался backing property (резервное свойство). Но здесь предлагаю применить более элегантный вариант с помощью делегата lazy, который использует ленивую инициализацию. Это такой механизм, который в лямбде принимает в нашем случае inflate() и возвращает созданный объект, который будет создан при первом обращении к нему.

2024-10-25 16:34 UTC, Churickoid commented on app/src/main/res/layout/activity_main.xml
> +            style="@style/Widget.Material3.Button.StyleNavButton"
В задании указано, что кнопки должны занимать всю ширину родителя и быть равные между собой

2024-10-25 16:34 UTC, Churickoid commented on app/src/main/res/values/styles.xml
> +    <style name="TextAppearance.AppCompat.StyleTitle14">
Неверный нейминг + не хватает наследования из задания

2024-10-25 16:34 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
>          enableEdgeToEdge()
Сейчас из-за этого параметра твои кнпоки перекрываются системным navigation bar, надо убрать

2024-10-26 12:06 UTC, Lapadoga commented
Внес правки, не до конца понял момент про 8 пункт задания, в настройках темы задал цвет статус бара и иконок

2024-10-26 14:32 UTC, Churickoid approved these changes
Всё верно, молодец! Оставил один коммент по неймингу, поправь в следующем ПР. По поводу 8 задания, треугольные скобки съели слова, добавил ковычки, должно стать понятнее.
Не увидел в теме изменение цвета у системной навигации. Добавь в следущем ПР тоже

2024-10-26 14:32 UTC, Churickoid commented on app/src/main/res/values/dimens.xml
> +    <dimen name="nav_button_radius">8dp</dimen>
Плохая практика повторять любые ресурсы по несколько раз, но с другим неймингом. Это касается и цветов, и строк,  и dimens. Сейчас 8dp, встречается дважды.  В таких случаях нужно удалить дубликат и дать более общее названию ресурсу, чтоб был понятен контекст.

2024-10-29 14:44 UTC, merged