RA-13 реализовал экран рецепта
Lapadoga/RecipeApp pull request #11
Opened 2024-12-21 10:04 UTC by Lapadoga

2024-12-21 19:04 UTC, Churickoid requested changes

2024-12-21 19:04 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +            rvIngredients.isNestedScrollingEnabled = false
По какой причине были добавлены два последних параметра? Это фиксит какой-то баг?

2024-12-21 19:04 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager" />
Давай добавим тестовые параметры, чтоб на макете всё было видно

2024-12-21 19:04 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:layout_marginVertical="@dimen/dimen_main"
Если нужен одинаковый margin со всех сторон, достаточно прописать margin

2024-12-21 19:04 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:layout_height="wrap_content"
У РесайклерВью не хватает заднего фона как на макете в фигме со скругленными краями

2024-12-22 10:02 UTC, Lapadoga commented
Внес описанные правки, использовал setHasFixedSize так как причитал, что это может оптимизировать динамический список при его изменении, setNestedScrollingEnabled - для того, чтобы избежать конфликтов прокрутки. Но, насколько понял, в данном случае они не нужны. 
Так же немного иначе сделал проверку на null (не вносил в initUI), так как показалось, что будет удобнее такая реализация

2024-12-23 08:53 UTC, Churickoid approved these changes
Молодец, по заданию всё верно! Единственное, там в дизайне divider занимает не всю длину айтема, поправь в следующем ПР

2024-12-23 09:09 UTC, merged