RA-14 добавил seek bar + правки прошлого ПР
Lapadoga/RecipeApp pull request #12
Opened 2024-12-24 11:03 UTC by Lapadoga

2024-12-24 15:55 UTC, Churickoid requested changes

2024-12-24 15:55 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/IngredientsAdapter.kt
> +            if (amount % 1 == 0F) "${amount.toInt()}" else String.format("%.1f", amount)
Вообще для чисел с точкой лучше использовать BigDecimal. Он позволяет точнее сравнивать и производить вычисления. Плюс есть встроенные методы для форматирования строк. Статья про BigDecimal: https://javarush.com/groups/posts/2274-kak-ispoljhzovatjh-bigdecimal-v-java

val totalQuantity = BigDecimal(ingredientCurrentCount) * BigDecimal(quantity)

val displayQuantity = totalQuantity
.setScale(1,RoundingMode.HALF_UP)
.stripTrailingZeros()
.toPlainString()

2024-12-24 15:55 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +            portionSize.text = initialQuantityString
Лучше просто у seekBar внутри xml установить progress = 1 . Тогда при создании вью должен сработать onProgressChanged. Если не сработает, то лучше после setOnSeekBarChangeListener устанавливать прогресс seekBar в коде, а не менять portionSize.text напрямую

2024-12-26 17:51 UTC, Lapadoga commented
По поводу второй правки: возможно, я что-то делал не так, но пробовал ставить прогресс в xml и задавать кодом после установки listener (sbPortions.progress = 1), но событие изменения не вызывалось

2024-12-27 09:34 UTC, Churickoid commented
По зааднию верно, молодец! У меня работает, если указывать после листенера. Просто по-умолчанию он устанавливает в xml единичку и ничего не меняется по итогу. Укажи в xml progress любой не равной 1
![image](https://github.com/user-attachments/assets/a5615bda-5c68-43d9-bd47-01217ccba746)

2024-12-28 10:55 UTC, merged